apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: property-hunt-nextjs-httproute
  namespace: twinkle-ns
  annotations:
    io.cilium/lb-pool: "cilium-lb-pool1"
spec:
  parentRefs:
    - name: property-hunt-nextjs-gateway
      namespace: twinkle-ns
  hostnames:
    - ashwija.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /property-hunt
      backendRefs:
        - name: property-hunt-nextjs-service
          port: 80
