apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: twinkle-ns
spec:
  selector:
    app:  {{ .Chart.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
